; note: most of the accent colors are set to the green of that color scheme, feel free to change it to your preferred color

[System24Cyan]
accent             = 33ccff
accent-active      = 33ccff
accent-inactive    = 1a1a1a
banner             = 33ccff
border-active      = 33ccff
border-inactive    = 335866
header             = 7fbfd1
highlight          = 0f0f0f
main               = 000000
notification       = 33ccff
notification-error = cc241d
subtext            = 9fb9c2
text               = e6f7ff
