$primary_paletteKeyColor = 33ccff
$secondary_paletteKeyColor = 33ccff
$tertiary_paletteKeyColor = 33ccff
$neutral_paletteKeyColor = 000000
$neutral_variant_paletteKeyColor = 000000
$background = 000000
$onBackground = e6f7ff
$surface = 000000
$surfaceDim = 000000
$surfaceBright = 0a0a0a
$surfaceContainerLowest = 000000
$surfaceContainerLow = 000000
$surfaceContainer = 000000
$surfaceContainerHigh = 000000
$surfaceContainerHighest = 050505
$onSurface = e6f7ff
$surfaceVariant = 101010
$onSurfaceVariant = a0c7d4
$inverseSurface = e6f7ff
$inverseOnSurface = 000000
$outline = 33ccff
$outlineVariant = 151515
$shadow = 000000
$scrim = 000000
$surfaceTint = 33ccff
$primary = 33ccff
$onPrimary = 000000
$primaryContainer = 0f3a47
$onPrimaryContainer = dff7ff
$inversePrimary = 66d9ff
$secondary = 33ccff
$onSecondary = 000000
$secondaryContainer = 0f3a47
$onSecondaryContainer = dff7ff
$tertiary = 33ccff
$onTertiary = 000000
$tertiaryContainer = 0f3a47
$onTertiaryContainer = dff7ff
$error = cc241d
$onError = ffffff
$errorContainer = 3a0d0b
$onErrorContainer = ffd9d6
$primaryFixed = 33ccff
$primaryFixedDim = 1aa3cc
$onPrimaryFixed = 000000
$onPrimaryFixedVariant = dff7ff
$secondaryFixed = 33ccff
$secondaryFixedDim = 1aa3cc
$onSecondaryFixed = 000000
$onSecondaryFixedVariant = dff7ff
$tertiaryFixed = 33ccff
$tertiaryFixedDim = 1aa3cc
$onTertiaryFixed = 000000
$onTertiaryFixedVariant = dff7ff
$term0 = 1a1a1a
$term1 = cc241d
$term2 = 8ec07c
$term3 = fabd2f
$term4 = 33ccff
$term5 = b48ead
$term6 = 8ecae6
$term7 = e6f7ff
$term8 = 555555
$term9 = ff5f5f
$term10 = a3f7bf
$term11 = f9e79f
$term12 = 66d9ff
$term13 = cba6f7
$term14 = a6e3ff
$term15 = ffffff
$rosewater = e6f7ff
$flamingo = dff7ff
$pink = 9fe7ff
$mauve = 66d9ff
$red = cc241d
$maroon = ff5f5f
$peach = ff8c42
$yellow = f9e79f
$green = 8ec07c
$teal = 8ecae6
$sky = 66d9ff
$sapphire = 33ccff
$blue = 33ccff
$lavender = 66d9ff
$klink = 33ccff
$klinkSelection = 33ccff
$kvisited = 66d9ff
$kvisitedSelection = 66d9ff
$knegative = cc241d
$knegativeSelection = cc241d
$kneutral = e6f7ff
$kneutralSelection = e6f7ff
$kpositive = 8ecae6
$kpositiveSelection = 8ecae6
$text = e6f7ff
$subtext1 = a0c7d4
$subtext0 = 6e8c95
$overlay2 = 33ccff
$overlay1 = 289fc7
$overlay0 = 1a6f8a
$surface2 = 0a0a0a
$surface1 = 050505
$surface0 = 000000
$base = 000000
$mantle = 000000
$crust = 000000
$success = 8ecae6
$onSuccess = 000000
$successContainer = 103844
$onSuccessContainer = dff7ff
